// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQWHWOxV-dL8zm1GPAKjEZkRbFAwDbJY',
    appId: '1:713279102893:web:f8da289c0671469ae84b24',
    messagingSenderId: '713279102893',
    projectId: 'seouldata',
    authDomain: 'seouldata.firebaseapp.com',
    storageBucket: 'seouldata.appspot.com',
    measurementId: 'G-NWXJD2436Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bxfsHZPzYmTago1sDANx8DVIEsammBg',
    appId: '1:713279102893:android:a647c683fe02f154e84b24',
    messagingSenderId: '713279102893',
    projectId: 'seouldata',
    storageBucket: 'seouldata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHVQmpM4z1kN2gvs_X5_bPw_PYFG1klo',
    appId: '1:713279102893:ios:aa71ba3b77c8f546e84b24',
    messagingSenderId: '713279102893',
    projectId: 'seouldata',
    storageBucket: 'seouldata.appspot.com',
    iosClientId: '713279102893-jt1sopu6f2nsgq794escv3pp1rh9rpp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.wbex2',
  );
}
